# Generated by Django 3.2.3 on 2021-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField()),
                ('city', models.TextField(max_length=20)),
                ('country', models.TextField(max_length=20)),
                ('Degree', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
