# Generated by Django 3.2.3 on 2021-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='github',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skype',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.URLField(default='#'),
        ),
    ]
