# Generated by Django 3.2.3 on 2021-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20210528_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='instagram',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='twitter',
            field=models.URLField(default='#', null=True),
        ),
    ]
